### ISSUE TITLE
IR decode in 8051 Example

### ISSUE THREAD

**Issue by wudihuanx** [irext/examples#10]
您好，请问在CC254X的应用案例中，是如何调用IR Decode 程式的？
没有找到入口，请帮忙指点一下。

**Comment by wudihuanx** [comment]
另外，还想请教一下，在离线解码过程中，subCate : 命令控制码样本类型(0: 2/4进制码， 1: 8/16进制码)，这个参数该从哪里获取呢？

**Comment by strawmanbobi** [comment]
CC254X example 好像是一个不完全的 example，请参考 CC265X。具体入口在  simpleBLEPeripheral.c，串口接收到命令之后，会调用 IRext 的 API。
具体单片机的启动过程请自行参考网上的学习教程，单片机是一个小系统，需要了解 bootloader 等原理之后再看代码（绝对不是 Windows / Linux 程序那样仅仅是一个 main 函数）。

subCate 的获取请参考文档的 WebAPI，从索引 API 当中取得。

请认真看文档。

**Comment by wudihuanx** [comment]
离线码库解码情况下怎么从webAPI获得subCate？文档我是看过的，subCate : 命令控制码样本类型(0: 2/4进制码， 1: 8/16进制码)这段注释本身就是在webAPI里摘录的啊。
