### ISSUE TITLE
离线解码如何获取subCate

### ISSUE THREAD

**Issue by wudihuanx** [irext/examples#12]
如题，问题被你关闭了，我没法再开，所以再重新起一个问题。

**Comment by strawmanbobi** [comment]
不好意思，你前一个问题的追加我没看到，所以在这里回复你。
目前如果是纯离线环境的话，是没有 API 支持的（API只支持从服务端调用）。
但是数据库里有一个 sqlite 版本的离线码库，如果你用的是 C 语言开发环境，可以使用 sqlite3 的库或者源代码集成到自己的产品，并且通过 sqlite3 + SQL 从 IRext sqlite 数据库里进行索引。需要自己对数据表的逻辑关系进行理解。从 category 到 brand，最后到 remote_index 层级，然后在 remote_index 序列里提取 subCate。
如果有需要，你可以加我微信，在线支持。

**Comment by wudihuanx** [comment]
好的，明白了。
我先按照这个思路去学习一下，后续有需要再请您帮忙！
感谢！
