### ISSUE TITLE
AC Status alway same

### ISSUE THREAD

**Issue by nguyenvanquan7826** [irext/examples#13]
Hi, thank for your projects, I download and try run android app and count not remote my AC. It alway turn off. Please fix it. Thank you.

**Comment by strawmanbobi** [comment]
The Android example only shows how user get start with the SDK all the way from remote indexing, binary downloading and IR 
 wave decoding, WITHOUT any usable production implementations including maintaining the AC status.
You have to read through the document, design and implement the product APP yourself.
Thanks.
