### ISSUE TITLE
JAVA WINDOWS 环境， libirda_decoder.so 文件

### ISSUE THREAD

**Issue by LBWhub** [irext/examples#14]
你好，我需要在 JAVA（非android） WINDOWS 环境下调用 libirda_decoder.so 文件，但是 WINDOWS 环境无法调用 .so 文件，这怎么解决呢，能否发布一份 libirda_decoder.so 文件对应的 .dll 文件呢？

**Comment by strawmanbobi** [comment]
你好，请下载 https://github.com/irext/core 工程，git clone git@github.com:irext/core.git
在 ir_decoder 里有 ir_decoder.sln，支持使用 VS 2019 导入，可自行编译出 dll 文件。
