### ISSUE TITLE
Android

### ISSUE THREAD

**Issue by clanaid** [irext/examples#2]
请问jni库的的接口类是定义哪些方法，README文档和demo里的不太一致

**Comment by clanaid** [comment]
我运行demo，遥控器保存后，打开加载的时候openFile总是返回-1失败了

**Comment by strawmanbobi** [comment]
您好，我最近在更新关于 JNI 的文档，大概这周能 ready，到时候 release 出来给你。你暂时可以参考 Android example。注意 Android APP 上你需要手动去系统设置里给 APP 赋予 sdcard 写权限，才能正常下载码库和打开，它默认是不会弹出来提示框让你授权的。谢谢。

**Comment by clanaid** [comment]
好的，我运行demo是在Android5.0系统的，权限不需授权，我看到码库已经是正常下载保存了，文件路径也都对了，File读取打开是正常的，就是我rdecode.openFile失败了，还有我尝试手动读取文件后将里面的数据通过openBinary也一样是失败返回-1

**Comment by clanaid** [comment]
还有请问下，电视/机顶盒类的没有频道+/-按钮的映射吗？

**Comment by strawmanbobi** [comment]
那我今天帮你看看那个demo是不是正常运行，如果有的话，我会修复bug；
电视机没有频道切换的功能（现在电视机已经收不到频道了，都是通过机顶盒来接收的）
机顶盒目前也没有频道+ - 但是可以直接输入数字切换频道

**Comment by clanaid** [comment]
好的感谢

**Comment by strawmanbobi** [comment]
Hi，您好，昨天我发布了 0.2.0 版本，请到 https://irext.net 或者到 github 上更新下 Android 的客户端，安装的时候请确保是 0.2.0 的版本 （0.1.4目前已经拿不到码库了，服务端修改过了）。
谢谢。

**Comment by strawmanbobi** [comment]
另外 JNI 的代码也针对这版做了修正，测试通过的。

**Comment by clanaid** [comment]
Ok

**Comment by strawmanbobi** [comment]
如果觉得满意的话，请麻烦给 https://github.com/irext/irext 加个小星星哦。谢谢。

**Comment by clanaid** [comment]
请问离线数据已经是最新的吗，是mysql吗

**Comment by strawmanbobi** [comment]
是的，mysql的
