### ISSUE TITLE
JNI中irACGetTemperatureRange返回的类与AndroidDemo的不一致

### ISSUE THREAD

**Issue by clanaid** [irext/examples#3]
![image](https://user-images.githubusercontent.com/7777205/55276450-ce85ff80-532e-11e9-9d62-043a0584555a.png)

**Comment by strawmanbobi** [comment]
已查，是因为 decode_core 升级到 0.2.0 之后并没有把 source code 同步到 Android 的示范工程里；
不过应该不会影响， Android 示范工程里 jni 代码只是展示源码，实际起作用的是 libJni 里的预编译共享库，而这些共享库是基于 decode_core 编译出来的，版本已经是 0.2.0。
已经做 update。
