### ISSUE TITLE
function_id问题

### ISSUE THREAD

**Issue by yuanchaowang** [irext/examples#4]
感谢提供的irext红外库，在学习源码的时候，有以下问题
1、在ir_ac_parse_parameter.c里面的函数parse_function_1里面，可以看到function_id对应的数据是存放在数组function1->comp_data偏移为function_id的位置。但是在最终使用的时候，又是从funtion - 1里面去取数据，两边匹配不上

2、想明白 风向枚举定义：SWING_TYPE_NORMAL SWING_TYPE_SWING_ONLY SWING_TYPE_NOT_SPECIFIED的区别

**Comment by strawmanbobi** [comment]
您好。第一个问题容我稍微 review 下代码，写得太久了，忘记了。
第二个问题：SWING_TYPE_NORMAL 就是支持扫风和定向风两种模式；SWING_TYPE_SWING_ONLY 就是只支持扫风，不支持定向风。SWING_TYPE_NOT_SPECIFIED 是指码库里没指明支持什么。所以不能操纵风向或者扫风。
