### ISSUE TITLE
控制台的一些操作问题

### ISSUE THREAD

**Issue by shengMR** [irext/examples#6]
你好，目前我在控制台上遇到了一个问题，就是我SDK页面新增一个Android项目，之后遇到不能编辑的问题，可能这不能编辑是对的操作，但是此项目不能被删除，并且在有此项目的情况下，不能再重新新增一个新的Android项目，之后我又尝试新增一个Web项目是可以的，但是也是只能创建一个并且不能删除

**Comment by strawmanbobi** [comment]
看了下，Android 会根据 package name，signature 以及 admin_id 作为主键去注册，也就是说同一个 admin+package_name+signature 只能注册一次。
可以考虑加一个删除功能，明天来开发，上线了通知你。

**Comment by strawmanbobi** [comment]
已经添加删除功能。
