### ISSUE TITLE
Android-example运行出错

### ISSUE THREAD

**Issue by figo-fe** [irext/examples#7]
你好，首先感谢作者创造这个伟大的作品！

运行Android-example发现一些问题：
1. 源码里的key和secret应该是失效了无法获取设备列表，我把包名、key、secret修改为自己注册的sdk可以正常运行，建议修正example源码可以直接run起来

2. 启动界面、添加设备操作正常，添加后点击添加的设备，App Crash提示 `/data/irext/libirda_decoder.so not found`

3. irext-android-example_0.2.2.apk 在点击添加的设备时也会crash，可能与2的问题类似

4. 如果直接使用ir-decode-android-jni-lib_0.2.2编译好的so，那么 sdk中 libpath如何修改
```
// 此处如何改
private IRDecode() {
    String libPath = "/data/irext/libirda_decoder.so";
    System.out.println("loading decode library " + libPath);
    System.load(libPath);
}
```

再次感谢！

**Comment by figo-fe** [comment]
我想把码库(bin)内置到包里，应该怎样操作呢？
我尝试过：将bin文件放到 src/main/assets/bin/xxx.bin 目录下，然后参考demo showRemote `binFileName = "/assets/bin/xxx.bin" `，但是打开失败，应该如何操作。

另外：
- showRemote方法里用so的方法载入bin，又用java载入了一次，这是出于什么考虑，不太理解
- openFile时为什么要传id和subId，一个bin文件不是和id,subId已经对应了么
- 希望能够了解工作流程，有没有流程图可参考

ps 我是前端开发，Android不熟，以上问题都经过了无数次尝试和搜索，依然没有找到答案，望指点，谢谢！

**Comment by figo-fe** [comment]
关于引入so的问题我已经解决：
1. 将so放到jniLibs目录
2. 配置Gradle将jniLibs加入
3. 在sdk中修改初始化代码如下
```
private IRDecode() {
    System.loadLibrary("irdadecoder");
}
```
已经没有报错也不crash，应该是ok了

**Comment by strawmanbobi** [comment]
1. android example 会 crash 的问题，已经解决，请尝试使用最新的源码或者 released apk（之前把 java web 的 jni 和 android 的搞混了，导致上述问题）。
2. 码库内置建议使用 sdcard 上的位置存放 binary 和 db。或者把 binary 和 db 打包 zip 编译到 assets，在 APP第一次运行时把 assets 当中的 zip 解压缩到 sdcard。
3. showRemote 里面打开文件流应该是一个 bug，后续去掉。
4. 在 JNI 层面进行 open 的时候传入的是 category_id 和 sub_cate，其中 category 会告诉解码核心当前的遥控码是空调（状态码）还是非空调（命令码），二者在解码核心当中处于两个完全不同的大分支。sub_cate 只作用于命令码，因为命令码分四进制码和十六进制码，主要是用来区分这个。
5. 解码工作流暂时没有，这个牵涉到码库压缩算法和结构，不过后续会考虑补一下，方便大家理解解码核心的逻辑。
6. 就算是 Android 开发也不会了解遥控领域的东西啊，万能遥控属于当代黑科技之一，网上基本搜不到多少信息，不然这项目就没价值了。
