### ISSUE TITLE
添加电视、盒子设备报错

### ISSUE THREAD

**Issue by Liweiwei2Anna** [irext/examples#8]
12-09 15:15:05.120 26744 26744 E AndroidRuntime: java.lang.SecurityException: Failed to find provider null for user 0; expected to find a valid ContentProvider for this authority
12-09 15:15:05.120 26744 26744 E AndroidRuntime: 	at android.os.Parcel.createException(Parcel.java:1953)
12-09 15:15:05.120 26744 26744 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1921)
12-09 15:15:05.120 26744 26744 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1871)
12-09 15:15:05.120 26744 26744 E AndroidRuntime: 	at android.content.IContentService$Stub$Proxy.notifyChange(IContentService.java:812)
12-09 15:15:05.120 26744 26744 E AndroidRuntime: 	at android.content.ContentResolver.notifyChange(ContentResolver.java:2149)
12-09 15:15:05.120 26744 26744 E AndroidRuntime: 	at android.content.ContentResolver.notifyChange(ContentResolver.java:2100)
12-09 15:15:05.120 26744 26744 E AndroidRuntime: 	at android.content.ContentResolver.notifyChange(ContentResolver.java:2070)
12-09 15:15:05.120 26744 26744 E AndroidRuntime: 	at com.activeandroid.Model.save(Model.java:162)
12-09 15:15:05.120 26744 26744 E AndroidRuntime: 	at net.irext.ircontrol.bean.RemoteControl.createRemoteControl(RemoteControl.java:190)
12-09 15:15:05.120 26744 26744 E AndroidRuntime: 	at net.irext.ircontrol.ui.fragment.IndexFragment.saveRemoteControl(IndexFragment.java:191)
12-09 15:15:05.120 26744 26744 E AndroidRuntime: 	at net.irext.ircontrol.ui.fragment.IndexFragment.access$1700(IndexFragment.java:44)
12-09 15:15:05.120 26744 26744 E AndroidRuntime: 	at net.irext.ircontrol.ui.fragment.IndexFragment$MsgHandler.handleMessage(IndexFragment.java:287)
12-09 15:15:05.120 26744 26744 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:112)
12-09 15:15:05.120 26744 26744 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:216)
12-09 15:15:05.120 26744 26744 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7625)
12-09 15:15:05.120 26744 26744 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-09 15:15:05.120 26744 26744 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
12-09 15:15:05.120 26744 26744 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
12-09 15:15:05.120 26744 26744 E AndroidRuntime: Caused by: android.os.RemoteException: Remote stack trace:
12-09 15:15:05.120 26744 26744 E AndroidRuntime: 	at com.android.server.content.ContentService.notifyChange(Landroid/net/Uri;Landroid/database/IContentObserver;ZIII)V(libmapleservices.so:5590557)
12-09 15:15:05.120 26744 26744 E AndroidRuntime: 	at android.content.IContentService$Stub.onTransact(ILandroid/os/Parcel;Landroid/os/Parcel;I)Z(libmapleframework.so:4973845)
12-09 15:15:05.120 26744 26744 E AndroidRuntime: 	at com.android.server.content.ContentService.onTransact(ILandroid/os/Parcel;Landroid/os/Parcel;I)Z(libmapleservices.so:5812809)
12-09 15:15:05.120 26744 26744 E AndroidRuntime: 	at android.os.Binder.execTransact(IJJI)Z(libmapleframework.so:6089041)

**Comment by Liweiwei2Anna** [comment]
没有ContentProvider啊

**Comment by Liweiwei2Anna** [comment]
换了个机型，可以了

**Comment by strawmanbobi** [comment]
OK，遇到问题再看。
