### ISSUE TITLE
Cannot try the win-32 example

### ISSUE THREAD

**Issue by theRemoter** [irext/examples#9]
Hello

I am trying to run the win-32 example though it doesn't start.
it says:
"...\win32-example\DecodeTestWin\DecodeTestWin.vcxproj" could not be found."

and indeed, there is no such file `DecodeTestWin.vcxproj` inside the folder `DecodeTestWin`.
it looks like in the gitignore, this file is being ignored.

**Comment by strawmanbobi** [comment]
Let me check, it might be a legacy file I used to run decode executable sample however it is not included in git files.

**Comment by strawmanbobi** [comment]
Dear theRemoter,
I have rebuilt the win32 example and uploaded to github, please clone it again.
Sorry for previous mistake, and really thanks for pointed it out.
